# Generated by Django 5.0.6 on 2026-05-30 04:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('categories', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='category',
            old_name='color',
            new_name='default_color',
        ),
    ]
